# Generated by Django 3.0 on 2020-11-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20201117_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usernm',
            new_name='userName',
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
