# Generated by Django 3.1.2 on 2020-11-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_auto_20201117_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
